### ISSUE TITLE
src/key.cpp:134: {anonymous}::CECKey::CECKey(): Assertion `pkey != __null' failed

### ISSUE THREAD

**Issue by robertgdev** [vertcoin/vertcoin-old#6]
I have built the qt-version of vertcoin on Fedora20 by doing the following (this is the first time I've ever compiled a QT program, so it may be that I'm doing something wrong): 

qmake-qt5
make clean
make
./vertcoin-qt

and I get the following: 

./vertcoin-qt 
libpng warning: iCCP: known incorrect sRGB profile
vertcoin-qt: src/key.cpp:134: {anonymous}::CECKey::CECKey(): Assertion `pkey != __null' failed.

Please advise. If I can help diagnose the problem any further, please let me know what to do.

**Comment by Paul-Bradley** [comment]
Hi,

The latest makefile should work with qmake-qt5, but can you also try
qmake-qt4 (or just plain qmake) and see what happens? Someone else reported
something similar recently, and it was fixed by building with the qt4 qmake.

**Comment by robertgdev** [comment]
I tried qmake-qt4 before that and got exactly the same issue. I then switched to qmake-qt5 since I figured "newer must be better" :-) ... so in terms of this issue, there is no difference between qt4 and qt5.

**Comment by Paul-Bradley** [comment]
Ok, looks like it's because the Fedora openssl builds don't implement one
of the elliptic curve functions needed (secp256k1) - it's a licensing
thing. Here's a patch for you:

In the main vertcoin folder (so, at a level where if you do ls you can see
subdirectories contrib, src, doc, share etc)

wget http://pastebin.com/raw.php?i=iFYJsgus -O patch

patch -p1 <patch

rm patch

qmake

make

Incidentally, I did build against qt4 (installed qt4-dev-tools on ubuntu,
not sure what that would be on fedora), so if it still doesn't build after
patching (and it's not just a straight dependency issue) try building
against qt4 too.

Let me know if you have any more issues.

Paul

**Comment by robertgdev** [comment]
Works like a charm! Thanks for the awesome support. 

Robert

**Comment by FRED-E** [comment]
Thanks! It works also for the feathercoin client on Fedora 20.
