### ISSUE TITLE
Minimum txfee in vertcoind?

### ISSUE THREAD

**Issue by dayreiner** [vertcoin/vertcoin-old#8]
Been trying to get sendmany to work with some small transactions, but I've run in to a weird issue when the txfee is set below 0.001 or to zero -- all transactions fail with an insufficient funds error. 

Is there a minimum 0.001 txfee enforced in vertcoind?

**Comment by Paul-Bradley** [comment]
I'm guessing for a faucet? In main.cpp around line 755:

// Don't accept it if it can't get into a block
        int64 txMinFee = tx.GetMinFee(1000, true, GMF_RELAY);
        if (fLimitFree && nFees < txMinFee)
            return error("CTxMemPool::accept() : not enough fees %s, %"
PRI64d" < %"PRI64d,
                         hash.ToString().c_str(),
                         nFees, txMinFee);

You could bypass that and recompile a custom vertcoind, but it's entirely
at your own risk - the transactions may never make it into a block, and if
they do make it in, the time that takes could be arbitrarily long (and
other nodes may not relay them at all) at which point you're in a sticky
spot because you can't double-spend them, so either you could import the
privkeys in another wallet and try again, or if other nodes had relayed
them but no-one had mined them, even that might not work (because the other
nodes wouldn't relay the double-spend).

If it's a faucet and you're creating lots of very small TXs, I'd just
sendmany once a day and pay the fees.

**Comment by dayreiner** [comment]
Thanks. No, this wasn't for a faucet -- side project for an autodonation daemon to distribute donations sent to a central address to p2pool miners that I haven't had much time to work on. Since donations were spread across small outputs among miner addresses I was running in to some calculation errors when trying to execute a sendmany with low/no fees using vertcoind. Thanks, this can be closed.
